export const styles = {
	container: {
		flex: 1,
	},

	btn: {
		margin: 20,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#06f',
		width: 85,
		height: 85,
		borderRadius: 50,
		borderWidth: 5,
		borderColor: '#44e736',
	},
	btnConatiner: {
		margin: 10,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#06f',
		width: 95,
		height: 95,
		borderRadius: 50,
		borderWidth: 11,
		borderColor: '#ffffff',
	},
	btntext: {
		fontSize: 30,
		fontWeight: 'bold',
		color: '#fff',
	},
	modalInput: {
		position: 'absolute',
	},
	input: {
		height: 40,
		borderColor: '#ccc',
		borderWidth: 1,
		marginBottom: 10,
		alignSelf: 'stretch',
		paddingHorizontal: 5,
	},
	text: {
		marginRight: 'auto',
		fontSize: 20,
		marginBottom: 10,
	},
	btnDeleteContainer: {
		flexDirection: 'row',
		marginLeft: 'auto',
		margin: 10,
		height: 40,
		alignItems: 'center',
		backgroundColor: '#b83e3e',
		paddingHorizontal: 10,
		padding: 5,
		borderRadius: 5,
	},
	textDelete: {
		fontSize: 20,
		color: '#eee',
	},
	productContanier: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
	},
	image: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	loader: {
		backgroundColor: '#eaf5ea',
		borderRadius: 50,
	},
	textLog: {
		fontSize: 20,
		color: '#943636',
	},
	textLogDark: {
		fontSize: 20,
		color: '#ec940f',
		fontWeight: '600',
	},
	logTouch: {
		flexDirection: 'row',

		width: 90,
	},
	logTouchDark: {
		flexDirection: 'row',
		width: 90,
	},
	btnConatinerDark: {
		margin: 10,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#c49f26',
		width: 105,
		height: 105,
		borderRadius: 50,
		borderWidth: 11,
		borderColor: '#c49f26',
	},
	imageDark: {
		width: '100%',
		height: '100%',
		resizeMode: 'contain',
	},
	btnDark: {
		margin: 20,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#cfaf21',
		width: 95,
		height: 95,
		borderRadius: 50,
		borderWidth: 5,
	},
	textDark: {
		marginRight: 'auto',
		fontSize: 20,
		marginBottom: 10,
		color: '#eba714',
	},
	inputDark: {
		height: 40,
		borderColor: '#eba714',
		borderWidth: 1,
		marginBottom: 10,
		alignSelf: 'stretch',
		paddingHorizontal: 5,
		color: '#fff',
	},
}
